default_platform(:ios)

platform :ios do
  desc "Run Jest tests"
  lane :test do
    Dir.chdir("..") do
      sh("yarn test")
    end
  end

  desc "Build the iOS app"
  lane :build do
    cocoapods(
      workspace: "TemplateReactNativeNewArch.xcworkspace"
    )
    gym(
      workspace: "TemplateReactNativeNewArch.xcworkspace",
      scheme: "TemplateReactNativeNewArch",
      configuration: "Release"
    )
  end
end
